
modLoader="javafml" 
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]]
modId="nyfscalendar" 
version="0.2.0" #mandatory
displayName="Nyfs Calendar"
credits="Thanks to the Mod Devs over at the Modded Mincraft Discord Server for all the Help!" #optional
authors="TheNyfaria" #optional
description='''
Adds a Calendar to the Game, Interacts with the Seasons
'''
